### ISSUE TITLE
Fix segfault

### ISSUE THREAD

**Issue by mohe2015** [mohe2015/green-lisp#154]
```
main_original
#0  0x0000555555555030 in green_lisp_demo@plt ()
#1  0x0000555555555156 in main ()

main
#0  0x00007ffff7fc7000 in green_lisp_demo () from ../libgreen-lisp.so
#1  0x0000555555555156 in main ()
```

it seems like the 7fff address is wrong as it doesnt use the plt for whatever reason

maybe stack is the problem? dont think so

**Comment by mohe2015** [comment]
I don't think the address is wrong (tested without aslr and the addresses seem legit). need to check the memory maps, should adjust the sections and program headers like the functioning shared library and also add the same assembly for testing (should be almost byte identical then)

**Comment by mohe2015** [comment]
TODO check if the shared library can still run on its own

Program headers most likely need to be page aligned for permissions
